"""Per-repository template for tools/build_notebook.py (NOTEBOOK_SPEC 1.1 §3.6 standalone carrier).

Only the task-specific prose and stage cells live here. Runtime install, the embedded pipeline
module, and the model pin/stage/verify cells are produced by the generator from repository
sources so they cannot drift from the package.
"""
# ruff: noqa: E501  -- markdown prose and code-cell text are kept on single lines for readable rendering

TEMPLATE = {
    "package": "mobilenetv4_classification_pipeline",
    "repo_name": "mobilenetv4-classification-pipeline",
    "stem": "mobilenetv4_classification",
    "notebook_name": "mobilenetv4_classification_colab.ipynb",
    "profile": "E2E",
    "mode": "GUIDED",
    "isolated_runtime": True,
    "infrastructure_labels": True,
    # The fleet's uv isolated-environment mechanism (generator /2.2): managed CPython, a
    # size- and SHA-256-verified uv wheel, and a lock compiled from the pyproject pins with
    # `uv pip compile pyproject.toml --python-version 3.12 --python-platform x86_64-manylinux_2_28 --generate-hashes
    # --only-binary :all: -o tutorials/requirements-colab.lock.txt`.
    "managed_python": "3.12.12",
    "uv": {
        "version": "0.12.15",
        "url": "https://files.pythonhosted.org/packages/1e/fd/432451d732917c49152a291de3ef171aa6b0f1a22d39780fb2c1f085ca4c/uv-0.12.15-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "bytes": 20081404,
        "sha256": "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60",
    },
    "lock": "tutorials/requirements-colab.lock.txt",
    "run_all": (
        "Selecting **Run all** in a fresh supported runtime builds an isolated hash-locked environment (nothing is installed into the notebook kernel, so no restart is needed), stages and digest-verifies the pinned "
        "snapshot, generates the deterministic synthetic sample image, validates it into an input manifest, classifies it with the "
        "pretrained head, writes the zero-shot evaluation report, downloads and digest-verifies the `Cleanlab/cifar-10-subset` tutorial "
        "dataset (a balanced per-class subset with a seeded 80/20 split), performs a bounded in-kernel fine-tuning run of a new "
        "classification head with AdamW and cross-entropy, exports the artifact (`model.safetensors` + `model-config.json`), reloads it "
        "from disk across a fresh boundary and evaluates the reloaded model on the held-out split against a majority-class baseline, "
        "and writes outputs and provenance. No repository clone, DIMER worker or service, credential, upload dialog or configuration "
        "edit is required (NOTEBOOK_SPEC 2.0 §5)."
    ),
    "byod": (
        "Two optional branches, both off by default and never part of the default path: `USE_BYOD = True` in Section 4 reads one "
        "image from `BYOD_PATH` (or, on Colab with the path left empty, from an upload dialog) that passes through the same validation, classification, evaluation-report and export cells as the synthetic sample; "
        "`USE_BYOD_DATASET = True` in Section 8 reads a `.zip` of class folders (or of `train/` and `val/` directories) from `BYOD_DATASET_PATH`, or from a Colab upload, that enters the "
        "same validation, seeded split, in-kernel fine-tuning, export, fresh-reload and held-out evaluation cells as the tutorial "
        "dataset. Expected formats, limits and privacy guidance are stated in the Prerequisites and in those cells; uploads stay "
        "inside this runtime."
    ),
    "pipeline_class": "MobileNetV4ClassificationPipeline",
    "weights_key": "mobilenetv4-conv-small",
    "runtime_imports": ["torch", "timm"],
    "title": "MobileNetV4-Conv-Small — DIMER image classification tutorial (standalone)",
    "badges": [
        (
            "GitHub",
            "https://img.shields.io/badge/GitHub-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/kurtvalcorza/mobilenetv4-classification-pipeline",
        ),
        (
            "Open In Colab",
            "https://colab.research.google.com/assets/colab-badge.svg",
            "https://colab.research.google.com/github/kurtvalcorza/mobilenetv4-classification-pipeline/blob/main/tutorials/mobilenetv4_classification_colab.ipynb",
        ),
        (
            "Hugging Face",
            "https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-timm%2Fmobilenetv4__conv__small.e2400__r224__in1k-ffcc4d?style=flat",
            "https://huggingface.co/timm/mobilenetv4_conv_small.e2400_r224_in1k",
        ),
        (
            "Upstream",
            "https://img.shields.io/badge/Upstream-huggingface%2Fpytorch--image--models-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/huggingface/pytorch-image-models",
        ),
        ("arXiv", "https://img.shields.io/badge/arXiv-2404.10518-b31b1b.svg", "https://arxiv.org/abs/2404.10518"),
    ],
    "capability": "ImageNet-1k single-label image classification (1000 classes) and in-kernel fine-tuning using the pinned `timm/mobilenetv4_conv_small.e2400_r224_in1k` weights",
    "intro": (
        "At inference the network maps one normalized 3×224×224 tensor to 1000 logits in a single forward pass; the "
        "pipeline applies a softmax and reports the argmax class plus the top-k classes with their scores. "
        "**In-kernel fine-tuning:** this notebook demonstrates both zero-shot base inference on ImageNet-1k classes and "
        "100% in-kernel classification head fine-tuning on custom classes using PyTorch AdamW optimization and cross-entropy "
        "loss. The upstream checkpoint supplies the pretrained backbone weights, and the carried pipeline module adds snapshot "
        "verification, input validation, head adaptation via `fit`, fresh-boundary reload verification, and the "
        "`top_k_accuracy`, `validate_inputs` and `evaluation_report` helpers. The default sample is a synthetic image "
        "generated in code; its prediction is demonstration (plumbing) evidence, not a production-quality or benchmark claim."
    ),
    "guided": {"opening": [(
        "**Who this notebook is for.** A learner who knows basic Python, has used Colab or Jupyter and has met the idea of an image classifier, and wants to see how a small pretrained convolutional network classifies an image, why its scores are not probabilities of being right, and how to adapt it to new classes by training only a new head. No prior experience with MobileNet, timm or fine-tuning is assumed; each term is explained where it first matters and again in the **Glossary** at the end. The audience is students and practitioners preparing their own small image-classification task; nothing here needs a GPU (the checkpoint is 15 MB).\n\n**Input → Model → Output.**\n\n| | Pretrained classification | Head fine-tuning |\n|---|---|---|\n| Input | one image (any Pillow-readable file up to 4096 px a side), resized to 256 px and centre-cropped to 224×224 | labelled images: a balanced subset of `Cleanlab/cifar-10-subset` (`frog`, `truck`) or your own class folders |\n| Model | MobileNetV4-Conv-Small backbone and its 1000-class ImageNet-1k head | the same backbone with a new linear head sized to your classes, trained with AdamW and cross-entropy |\n| Output | the argmax class and a top-5 list of softmax scores (never an abstention) | `model.safetensors` + `model-config.json`, reloaded from disk and scored on the held-out split against a majority-class baseline |\n\n**How to use this notebook.** Choose any runtime (CPU is enough), then **Runtime → Run all**. Run all completes in one pass: Section 1 installs nothing into the notebook's own Python, so no restart is needed. Sections 1–3 are **infrastructure** — the isolated environment, the carried pipeline module and the model snapshot — and their cells are collapsed; you may run them without studying them. The learning path starts in Section 4. Form fields (`# @param`) are the only values meant to be edited, and the defaults reproduce the default path. Before each principal result the notebook asks you to **Predict**; after it comes a collapsible **Check your reasoning** with a worked answer. No per-cell outputs of a hosted run are recorded in this repository yet, so the worked answers describe what the code guarantees and what to look for rather than quoting numbers; compare them with what your run prints. **Troubleshooting**, a **Glossary** and a **Conclusion** template are at the end. Writing your predictions down is optional.\n\n**Roadmap:** 1–3 infrastructure → 4 the synthetic sample (or your image) → 5 input validation and a deliberate refusal → 6 classify and read the top-5 *(core concept: softmax scores)* → 7 the evaluation report and why the gradient is `not-measurable` *(evaluation practice)* → 8 a labelled dataset and head fine-tuning *(core concept: what is trained)* → 9 fresh reload and held-out accuracy against the majority baseline *(evaluation practice)* → 10 export and provenance *(engineering)* → conclude."
    )]},
    "learning_objectives": (
        "install the pinned runtime, read what the carried pipeline module guarantees, resolve and digest-verify the "
        "immutable upstream model revision, generate a synthetic default input and validate it into an input manifest, "
        "run the supported task, read the argmax decision and the uncalibrated top-k softmax scores correctly, execute "
        "100% in-kernel fine-tuning on custom classes with AdamW and cross-entropy, export and fresh-reload fine-tuned "
        "artifacts, exercise an optional BYOD path, produce an evaluation report that is `sample-sanity` only when a "
        "ground-truth class index exists and `not-measurable` otherwise, and export machine-readable outputs plus provenance."
    ),
    "exclusions": (
        "object detection, segmentation, multi-label tagging, OCR, open-vocabulary classification, feature/embedding "
        "extraction. The base label space is fixed to the 1000 ImageNet-1k classes; an image whose subject is outside that "
        "space still receives a label unless adapted via in-kernel fine-tuning."
    ),
    "prerequisites": [
        "- **Learner:** basic Python and Colab or Jupyter familiarity; no prior experience with MobileNet, timm or fine-tuning. Softmax scores, top-k, the classification head, epochs, the majority-class baseline and held-out evaluation are explained where they are first used and again in the Glossary.",
        "- **Runtime:** a fresh supported **Linux x86_64** runtime (Google Colab, Kaggle or Linux Jupyter). Section 1 builds its own Python 3.12.12 environment from a hash-locked list of manylinux wheels, so the kernel's own Python version does not matter and nothing is installed into it; a Windows or macOS kernel is not supported. The default path runs on CPU and uses CUDA automatically when available; inference is float32 on both. **CPU is the natural default for this model:** the checkpoint is 15 MB and the repository's model card records a measured CPU smoke of 2.08 s for load plus one prediction (Intel Core Ultra 9 275HX, WSL venv); CUDA is used automatically when present but is not needed. The pinned `torch==2.14.0` install is the largest download of the run.",
        "- **Knowledge:** basic Python and PIL image handling; what a softmax over class logits is.",
        "- **Data:** the default sample for Sections 4–7 is a deterministic 256×256 RGB gradient generated in code, so no private data is needed. Section 8 downloads one public dataset archive on the default path: `Cleanlab/cifar-10-subset` (~986 KB, MIT licence) from the Hugging Face Hub at a pinned commit, refused on a SHA-256 mismatch; its 100 originals per class (`frog`, `truck`) are used after pixel-identical duplicates are removed, giving 160 training and 40 held-out images. BYOD is gated off by default so the sample path can run top-to-bottom without interaction. Single-image BYOD: set `USE_BYOD = True` and `BYOD_PATH` to a file in the runtime (works on Colab, Kaggle and Jupyter); on Colab an empty `BYOD_PATH` opens an upload dialog instead. Expected input: one image file decodable by Pillow (PNG/JPEG/WebP and similar), any colour mode, longest side at most 4096 px. Do not upload confidential or restricted data to a hosted notebook environment unless you are authorized to do so. Uploaded inputs remain in the notebook runtime; this pipeline does not send them to a third-party inference API.",
        "- **Dataset BYOD (Section 8):** one `.zip` (`BYOD_DATASET_PATH`, or a Colab upload) holding either `train/<class>/` and `val/<class>/` folders, or un-split `<class>/` folders that the notebook splits 80/20 with a fixed seed. Effective minimum: **2 classes**; with un-split folders **2 images per class** (one goes to validation), with explicit folders at least one training image per class and a non-empty `val/`. Images are `.png`, `.jpg`, `.jpeg`, `.webp` or `.bmp`; other files are counted and reported, never silently dropped; every refusal names the archive member and the rule.",
    ],
    "cells": [
        {
            "md": (
                "## 4. Generate the synthetic sample or optional BYOD\n\n"
                "The default sample is **synthetic**: a deterministic 256×256 RGB gradient built in code (red ramps left to "
                "right, green top to bottom, blue is their mean), so it needs no download and its SHA-256 is printed for the "
                "record. A gradient is not a photograph of any ImageNet class, so it has **no ground truth**: whatever label "
                "the model returns is a sanity check that the input contract, preprocessing and forward pass work, not a "
                "correctness measurement. BYOD is optional and disabled by default; when enabled, upload one image file and, "
                "if you know its ImageNet-1k class index (0–999), set `GROUND_TRUTH_INDEX` so the evaluation step can compute "
                "`top_k_accuracy`. Leave it at `-1` when the label is unknown. Set `BYOD_PATH` to an image already in the "
                "runtime (Colab, Kaggle or Jupyter); on Colab an empty path opens an upload dialog, and a cancelled or "
                "multi-file upload stops with a message instead of a bare error. Look for a dictionary naming the sample kind, "
                "its size and digest, and whether a ground-truth index was supplied.\n\n"
                "**Predict before running:** run the cell twice in your head. Will the `rgb_sha256` digest be the same on "
                "every run and every runtime? Why does that matter for a tutorial?"
            ),
            "code": (
                "import hashlib\n"
                "import io\n\n"
                "import numpy as np\n"
                "from PIL import Image\n\n"
                "import os\n"
                "from pathlib import Path\n\n"
                "USE_BYOD = False  # @param {{type:\"boolean\"}}\n"
                "BYOD_PATH = ''  # @param {{type:\"string\"}}\n"
                "GROUND_TRUTH_INDEX = -1  # @param {{type:\"integer\"}}\n"
                "SAMPLE_SIDE = 256\n\n\n"
                "def read_byod_file(path, kind, suffixes=None):\n"
                "    \"\"\"BYOD_PATH first (works on Colab, Kaggle and Jupyter); on Colab an empty path opens the upload dialog.\"\"\"\n"
                "    if path.strip():\n"
                "        source = Path(path.strip()).expanduser()\n"
                "        if not source.is_file():\n"
                "            raise FileNotFoundError(f'BYOD path {{str(source)!r}} does not exist or is not a file (relative paths start at {{os.getcwd()}}); give the path of one {{kind}}.')\n"
                "        name, data = source.name, source.read_bytes()\n"
                "    else:\n"
                "        try:\n"
                "            from google.colab import files\n"
                "        except ImportError:\n"
                "            raise RuntimeError(f'BYOD is on but its path field is empty, and the upload dialog exists only in Google Colab: copy the {{kind}} into this runtime (or attach it as a Kaggle dataset) and set the path field.') from None\n"
                "        uploaded = files.upload()\n"
                "        if len(uploaded) != 1:\n"
                "            raise ValueError(f'Upload exactly one {{kind}} (received {{len(uploaded)}} files; a cancelled dialog sends none). Run this cell again.')\n"
                "        name, data = next(iter(uploaded.items()))\n"
                "    if suffixes and not name.lower().endswith(suffixes):\n"
                "        raise ValueError(f'{{name}}: expected a {{kind}} ending in {{\" or \".join(suffixes)}}.')\n"
                "    return name, data\n\n\n"
                "if USE_BYOD:\n"
                "    image_name, image_bytes = read_byod_file(BYOD_PATH, 'image file')\n"
                "    try:\n"
                "        image = Image.open(io.BytesIO(image_bytes))\n"
                "        image.load()\n"
                "    except Exception as exc:\n"
                "        raise ValueError(f'{{image_name}}: Pillow cannot decode this file ({{exc}}); BYOD needs one PNG, JPEG, WebP or similar image.') from None\n"
                "    sample_kind = 'BYOD'\n"
                "else:\n"
                "    # Deterministic synthetic gradient: no randomness, so no seed is needed and the digest is stable.\n"
                "    ramp = np.linspace(0.0, 255.0, SAMPLE_SIDE)\n"
                "    red = np.tile(ramp, (SAMPLE_SIDE, 1))\n"
                "    green = red.T\n"
                "    blue = (red + green) / 2.0\n"
                "    array = np.rint(np.stack([red, green, blue], axis=-1)).astype(np.uint8)\n"
                "    image = Image.fromarray(array)\n"
                "    image_name = f'synthetic_gradient_{{SAMPLE_SIDE}}.png'\n"
                "    sample_kind = 'synthetic'\n\n"
                "if GROUND_TRUTH_INDEX != -1 and not 0 <= GROUND_TRUTH_INDEX < NUM_CLASSES:\n"
                "    raise ValueError(f'GROUND_TRUTH_INDEX must be -1 (unknown) or an ImageNet-1k class index in 0..{{NUM_CLASSES - 1}}, got {{GROUND_TRUTH_INDEX}}.')\n"
                "ground_truth = None if GROUND_TRUTH_INDEX == -1 else GROUND_TRUTH_INDEX\n"
                "sample_sha256 = hashlib.sha256(np.asarray(image.convert('RGB')).tobytes()).hexdigest()\n"
                "print({{'sample_kind': sample_kind, 'name': image_name, 'mode': image.mode, 'size': image.size, 'rgb_sha256': sample_sha256, 'ground_truth_index': ground_truth}})"
            ),
        },
        {
            "md": (
                "<details><summary>Check your reasoning</summary>Yes. The gradient is computed from `np.linspace` with no "
                "random numbers, so its pixels, and therefore its SHA-256, are identical on every run; the digest printed "
                "above is the one recorded in `outputs/{stem}_result.json`. A fixed, digest-identified input is what makes "
                "two runs comparable: if the prediction in Section 6 differs between runtimes, the input is ruled out and the "
                "difference comes from the device or library kernels.</details>"
            ),
        },
        {
            "md": (
                "## 5. Validate the input → input manifest\n\n"
                "`validate_inputs` is the pipeline's public validation stage: it applies exactly the checks `predict` "
                "applies — type, batch size 1..`MAX_BATCH`, image side 1..`MAX_IMAGE_SIDE` px, `top_k` 1..`NUM_CLASSES` — "
                "and returns an **input manifest** naming the schema and ceilings, each input's observed mode and size, "
                "and the verdict. The manifest is written to `outputs/{stem}_input_manifest.json`. To show what rejection "
                "looks like, the cell also validates a deliberately oversized image and records the pipeline's own error "
                "message as a finding. Inside the pipeline every accepted image is converted to RGB, resized to 256 px and "
                "center-cropped to 224×224 (`crop_pct = 0.875`, bicubic), so content near the border is cropped away; "
                "nothing else is dropped or altered."
            ),
            "code": (
                "import json\n"
                "import os\n\n"
                "os.makedirs('outputs', exist_ok=True)\n"
                "print({{'ceilings': {{'NUM_CLASSES': NUM_CLASSES, 'MAX_IMAGE_SIDE': MAX_IMAGE_SIDE, 'MAX_BATCH': MAX_BATCH}}}})\n"
                "input_manifest = validate_inputs(image, top_k=5, names=[image_name])\n"
                "# Demonstrate rejection on an input that breaks a ceiling; the finding is recorded, not swallowed.\n"
                "try:\n"
                "    validate_inputs(Image.new('RGB', (MAX_IMAGE_SIDE + 1, 8)))\n"
                "except ValueError as exc:\n"
                "    input_manifest['findings'].append({{'input': 'oversized-probe', 'verdict': 'rejected', 'message': str(exc)}})\n"
                "with open('outputs/{stem}_input_manifest.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(input_manifest, handle, indent=2, ensure_ascii=False)\n"
                "print(json.dumps(input_manifest, indent=2))"
            ),
        },
        {
            "md": (
                "## 6. Classify\n\n"
                "`predict` returns, per image, `predicted_index`/`predicted_label` and a `top_k` list of `{{label, index, "
                "score}}` entries **ordered by descending score** — rank position is the class ordering, and the exported "
                "files preserve it. The decision rule is `argmax` over the 1000 softmax scores (`decision_rule` in the "
                "result); the pipeline ships no acceptance threshold, and `score` is a softmax over uncalibrated logits, "
                "**not a calibrated probability**. A deployment that needs an abstain option must choose its own score "
                "cut-off on its own labelled data — downstream calibration is the caller's responsibility. Inference is "
                "deterministic given the same weights, device and library versions (no sampling, `model.eval()`); CPU, GPU "
                "and cuDNN kernel choices can reorder near-tied classes. Look for the ranked top-5 list.\n\n"
                "**Predict before running:** the gradient is not a photograph of any of the 1000 ImageNet classes. Will the "
                "model refuse to answer? Will the top-1 score be close to 1.0, or low and spread across several classes?"
            ),
            "code": (
                "result = pipe.predict(image, top_k=5)\n"
                "prediction = result['predictions'][0]\n"
                "print({{'decision_rule': result['decision_rule'], 'predicted_index': prediction['predicted_index'], 'predicted_label': prediction['predicted_label'], 'device': result['device'], 'source': result['source']}})\n"
                "for rank, item in enumerate(prediction['top_k'], start=1):\n"
                "    print(f\"{{rank:>2}}. index {{item['index']:>4}}  score {{item['score']:.4f}}  {{item['label']}}\")"
            ),
        },
        {
            "md": (
                "<details><summary>Check your reasoning</summary>The model never refuses: `predict` always returns the argmax "
                "of 1000 softmax scores, so a label appears even for an image with no subject. Whether the top-1 score is "
                "high or low says little about correctness — a softmax over uncalibrated logits can be confident on "
                "out-of-distribution input. Read the list as *which ImageNet classes the colours and smooth edges resemble*, "
                "not as an answer. This is why Section 7 refuses to compute a metric on this sample.\n\n"
                "**What to notice:** the scores are ordered, the five shown do not sum to 1 (the other 995 classes hold the "
                "rest), and `decision_rule` is `argmax` with no threshold.</details>"
            ),
        },
        {
            "md": (
                "## 7. Evaluate → evaluation report\n\n"
                "`evaluation_report` is the pipeline's public evaluation stage and always produces a report. When a "
                "ground-truth class index was supplied in Section 4 it carries `top_k_accuracy` (the repository's metric "
                "helper) at k=1 and k=5 with the verdict `sample-sanity` — a single-image tutorial metric with no dispersion "
                "estimate. On the synthetic default sample no metric exists, so the verdict is `not-measurable` and the "
                "report states what would make the task measurable: labelled photographs with ImageNet-1k class indices, "
                "for example a held-out sample of your own data scored against its majority-class baseline, or the "
                "ImageNet-1k validation set (whose upstream 73.756 % top-1 / 91.422 % top-5 at 224 px is quoted from the "
                "upstream card, not measured here). The report is written to `outputs/{stem}_evaluation_report.json`.\n\n"
                "**Predict before running:** with `GROUND_TRUTH_INDEX = -1`, which verdict will the report give, and what "
                "would change if you supplied a class index for a single BYOD photograph?"
            ),
            "code": (
                "targets = None if ground_truth is None else [ground_truth]\n"
                "report = evaluation_report(result, targets, sample_kind=sample_kind)\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(report, handle, indent=2, ensure_ascii=False)\n"
                "print(json.dumps(report, indent=2))\n"
                "if report['verdict'] == 'not-measurable':\n"
                "    print('No ground-truth class index was supplied, so top_k_accuracy is not computed; the prediction above is sanity evidence only.')"
            ),
        },
        {
            "md": (
                "<details><summary>Check your reasoning</summary>`not-measurable`: there is no ground truth, so no accuracy "
                "exists to report. With a BYOD photograph and its index the verdict becomes `sample-sanity` and "
                "`top_k_accuracy` at k=1 and k=5 is each either 0 or 1 — one image cannot estimate a rate, so it is a check "
                "that the plumbing agrees with your label, not a measurement of the model.</details>"
            ),
        },
        {
            "md": (
                "## 8. Dataset acquisition and in-kernel fine-tuning\n\n"
                "`pipe.fit(...)` implements 100% in-kernel adaptation: it builds the verified backbone from the snapshot, replaces the "
                "1000-class head with a new linear classifier sized to the target classes (`len(class_names)`), and trains with "
                "`torch.optim.AdamW` and cross-entropy loss. **What is trained:** with `TRAINABLE = \"head\"` (the default) only the "
                "new head's weights and bias learn — the 3.8 M backbone parameters are frozen and the network stays in eval mode, so its "
                "BatchNorm statistics are not overwritten by small batches; the head starts at zero, so the first loss is exactly "
                "ln(2) ≈ 0.693 and nothing is confidently wrong before training. `TRAINABLE = \"all\"` trains every parameter in train mode "
                "(full fine-tuning). The head initialisation and the shuffled batch order are seeded from `SEED`, so two runs on the same "
                "runtime give identical predictions; the cell prints the trainable and frozen parameter counts and the full recipe "
                "(`fine_tuning`), which is also written into `model-config.json`. No external worker repositories, CLI subprocesses, or "
                "unpinned dependencies are invoked.\n\n"
                "**Data Acquisition & BYOD:**\n"
                "- **Default Sample Dataset (`USE_BYOD_DATASET = False`):** Downloads "
                "[`Cleanlab/cifar-10-subset`](https://huggingface.co/datasets/Cleanlab/cifar-10-subset) (MIT license, ~986 KB) at a pinned "
                "commit and refuses it on a SHA-256 mismatch (a mismatch stops the notebook; nothing trains). The archive holds 400 images "
                "in 2 balanced classes (`frog`, `truck`) as `original_images/` and `darkened_images/` trees that are **pixel-identical "
                "copies of the same 100 pictures per class**, so the notebook removes exact duplicates before splitting (reported as "
                "`skipped_members['pixel_duplicate']`); the split then assumes the remaining images are independent, and `SUBSET_PER_CLASS` "
                "(100 = all originals) is split 80/20 by a seeded shuffle into 160 training and 40 held-out images. Only if the network is "
                "unreachable does the cell fall back to deterministic synthetic stripes, and then it says so in `dataset_source` and "
                "`result.json` (`dataset_fallback_used`).\n"
                "- **Bring Your Own Data (`USE_BYOD_DATASET = True`):** Upload a `.zip` archive containing either explicit `train/` and `val/` "
                "directories or un-split class folders (in which case a seeded 80/20 stratified split is performed automatically). "
                "Enforces >= 2 classes and >= 2 images per class. Set `BYOD_DATASET_PATH` to the `.zip` in the runtime (Colab, Kaggle "
                "or Jupyter); on Colab an empty path opens an upload dialog. Unused archive members are counted in `skipped_members`.\n\n"
                "Deployable fine-tuned artifacts (`model.safetensors` and `model-config.json`) are written atomically to `outputs/{stem}_finetuned`.\n\n"
                "**Predict before running:** which parameters will this run change — the whole network or only part of it? "
                "How many training and validation images will the default sample give after duplicates are removed? And where "
                "should the training loss start if the new head begins at zero on a 2-class task?"
            ),
            "code": (
                "import hashlib\n"
                "import io\n"
                "import random\n"
                "import urllib.request\n"
                "import zipfile\n\n"
                "USE_BYOD_DATASET = False  # @param {{type:\"boolean\"}}\n"
                "BYOD_DATASET_PATH = ''  # @param {{type:\"string\"}}\n"
                "SAMPLE_DATASET_URL = 'https://huggingface.co/datasets/Cleanlab/cifar-10-subset/resolve/bb5a7aabf1d14d2d1e3e49d0d8f917bda3622f75/CIFAR-10-subset.zip'\n"
                "SAMPLE_DATASET_SHA256 = '66f90a4f87d865e8eb653b62f10e754684075a32314177de76832349d4b1fb19'\n"
                "SEED = 42  # @param {{type:\"integer\"}}\n"
                "EPOCHS = 8  # @param {{type:\"integer\"}}\n"
                "BATCH_SIZE = 8  # @param {{type:\"integer\"}}\n"
                "LEARNING_RATE = 1e-3  # @param {{type:\"number\"}}\n"
                "TRAINABLE = 'head'  # @param ['head', 'all']\n"
                "VALIDATION_SPLIT = 0.2\n"
                "SUBSET_PER_CLASS = 100  # images per class kept from the sample after duplicate removal (100 = all originals)\n"
                "IMAGE_SUFFIXES = ('.png', '.jpg', '.jpeg', '.webp', '.bmp')\n"
                "\n"
                "train_images, train_targets = [], []\n"
                "val_images, val_targets = [], []\n"
                "zip_bytes = None\n"
                "dataset_fallback_used = False\n"
                "skipped = {{'not_an_image': 0, 'val_class_not_in_train': 0, 'pixel_duplicate': 0}}\n"
                "\n"
                "if USE_BYOD_DATASET:\n"
                "    zip_name, zip_bytes = read_byod_file(BYOD_DATASET_PATH, 'dataset .zip archive', ('.zip',))\n"
                "    dataset_source = f'BYOD: {{zip_name}}'\n"
                "else:\n"
                "    try:\n"
                "        req = urllib.request.Request(SAMPLE_DATASET_URL, headers={{'User-Agent': 'Mozilla/5.0'}})\n"
                "        with urllib.request.urlopen(req, timeout=30) as resp:\n"
                "            zip_bytes = resp.read()\n"
                "    except Exception as exc:  # network failure only; a digest mismatch is checked outside this block and fails closed\n"
                "        print(f'Warning: public sample dataset download failed ({{exc}}); falling back to deterministic synthetic stripes. The accuracy below is then about stripes, not photographs.')\n"
                "        zip_bytes = None\n"
                "        dataset_fallback_used = True\n"
                "        dataset_source = 'synthetic stripes fallback (sample download failed)'\n"
                "    if zip_bytes is not None:\n"
                "        actual_sha = hashlib.sha256(zip_bytes).hexdigest()\n"
                "        if actual_sha != SAMPLE_DATASET_SHA256:\n"
                "            raise ValueError(f'Sample dataset SHA-256 mismatch: expected {{SAMPLE_DATASET_SHA256}}, got {{actual_sha}} ({{len(zip_bytes)}} bytes from {{SAMPLE_DATASET_URL}}). The archive is not the pinned one; nothing is trained on it.')\n"
                "        dataset_source = f'Cleanlab/cifar-10-subset (MIT license, sha256:{{actual_sha[:16]}}...)'\n"
                "\n"
                "if zip_bytes is not None:\n"
                "    try:\n"
                "        archive = zipfile.ZipFile(io.BytesIO(zip_bytes))\n"
                "    except zipfile.BadZipFile:\n"
                "        raise ValueError(f'{{dataset_source}}: not a readable .zip archive.') from None\n"
                "    with archive as z:\n"
                "        # Security audit: reject directory traversal and absolute paths\n"
                "        for info in z.infolist():\n"
                "            if '..' in info.filename or info.filename.startswith(('/', '\\\\')):\n"
                "                raise ValueError(f'Security violation: illegal path in zip archive: {{info.filename}}')\n"
                "        members = [n for n in z.namelist() if not n.endswith('/') and not n.startswith('__MACOSX')]\n"
                "        names = [n for n in members if n.lower().endswith(IMAGE_SUFFIXES)]\n"
                "        skipped['not_an_image'] = len(members) - len(names)\n"
                "        if not names:\n"
                "            raise ValueError(f'No supported image files ({{\", \".join(IMAGE_SUFFIXES)}}) found in archive.')\n"
                "\n"
                "        def _open(member):\n"
                "            try:\n"
                "                return Image.open(io.BytesIO(z.read(member))).convert('RGB')\n"
                "            except Exception as exc:\n"
                "                raise ValueError(f'{{member}}: Pillow cannot decode this archive member ({{exc}}).') from None\n"
                "\n"
                "        # Pixel-identical copies (the sample ships every picture twice) are grouped before any split, so a held-out\n"
                "        # image never has its copy in training; the first member of each group is kept, the rest are counted.\n"
                "        _seen_pixels = {{}}\n"
                "        _unique = []\n"
                "        for n in names:\n"
                "            digest = hashlib.sha256(np.asarray(_open(n)).tobytes()).hexdigest()\n"
                "            if digest in _seen_pixels:\n"
                "                skipped['pixel_duplicate'] += 1\n"
                "                continue\n"
                "            _seen_pixels[digest] = n\n"
                "            _unique.append(n)\n"
                "        names = _unique\n"
                "\n"
                "        has_train = any('train/' in n.lower() for n in names)\n"
                "        has_val = any('val/' in n.lower() or 'valid/' in n.lower() for n in names)\n"
                "\n"
                "        def _class_from_path(p):\n"
                "            parts = p.strip('/').split('/')\n"
                "            return parts[-2] if len(parts) >= 2 else 'unknown'\n"
                "\n"
                "        if has_train and has_val:\n"
                "            train_names = [n for n in names if 'train/' in n.lower()]\n"
                "            val_names = [n for n in names if 'val/' in n.lower() or 'valid/' in n.lower()]\n"
                "            CUSTOM_CLASSES = sorted(list({{_class_from_path(n) for n in train_names}}))\n"
                "            if len(CUSTOM_CLASSES) < 2:\n"
                "                raise ValueError(f'Classification requires at least 2 distinct classes under train/, found {{CUSTOM_CLASSES}}')\n"
                "            cls_map = {{c: i for i, c in enumerate(CUSTOM_CLASSES)}}\n"
                "            for n in train_names:\n"
                "                train_images.append(_open(n))\n"
                "                train_targets.append(cls_map[_class_from_path(n)])\n"
                "            for n in val_names:\n"
                "                cls = _class_from_path(n)\n"
                "                if cls not in cls_map:\n"
                "                    skipped['val_class_not_in_train'] += 1\n"
                "                    continue\n"
                "                val_images.append(_open(n))\n"
                "                val_targets.append(cls_map[cls])\n"
                "            if not val_images:\n"
                "                raise ValueError(f'val/ holds no image of a class that is also under train/ ({{skipped[\"val_class_not_in_train\"]}} skipped); add validation images for {{CUSTOM_CLASSES}}.')\n"
                "        else:\n"
                "            class_to_files = {{}}\n"
                "            for n in names:\n"
                "                cls = _class_from_path(n)\n"
                "                class_to_files.setdefault(cls, []).append(n)\n"
                "            CUSTOM_CLASSES = sorted(list(class_to_files.keys()))\n"
                "            if len(CUSTOM_CLASSES) < 2:\n"
                "                raise ValueError(f'Classification requires at least 2 distinct classes to train, found {{len(CUSTOM_CLASSES)}}: {{CUSTOM_CLASSES}}')\n"
                "            cls_map = {{c: i for i, c in enumerate(CUSTOM_CLASSES)}}\n"
                "            rng = random.Random(SEED)\n"
                "            for cls, files_in_class in class_to_files.items():\n"
                "                if len(files_in_class) < 2:\n"
                "                    raise ValueError(f'Class {{cls!r}} has fewer than 2 images ({{len(files_in_class)}}); cannot perform train/val split.')\n"
                "                f_list = list(files_in_class)\n"
                "                rng.shuffle(f_list)\n"
                "                if not USE_BYOD_DATASET and SUBSET_PER_CLASS:\n"
                "                    f_list = f_list[:SUBSET_PER_CLASS]\n"
                "                n_val = max(1, int(len(f_list) * VALIDATION_SPLIT))\n"
                "                for f in f_list[n_val:]:\n"
                "                    train_images.append(_open(f))\n"
                "                    train_targets.append(cls_map[cls])\n"
                "                for f in f_list[:n_val]:\n"
                "                    val_images.append(_open(f))\n"
                "                    val_targets.append(cls_map[cls])\n"
                "else:\n"
                "    CUSTOM_CLASSES = ['synthetic_horizontal_stripe', 'synthetic_vertical_stripe']\n"
                "    for cls_idx, pattern in enumerate(['horizontal', 'vertical']):\n"
                "        for i in range(6):\n"
                "            arr = np.zeros((SAMPLE_SIDE, SAMPLE_SIDE, 3), dtype=np.uint8)\n"
                "            if pattern == 'horizontal':\n"
                "                arr[::16, :, 0] = 255\n"
                "                arr[:, :, 2] = (i * 30) % 255\n"
                "            else:\n"
                "                arr[:, ::16, 1] = 255\n"
                "                arr[:, :, 2] = (i * 30) % 255\n"
                "            img = Image.fromarray(arr)\n"
                "            if i < 4:\n"
                "                train_images.append(img)\n"
                "                train_targets.append(cls_idx)\n"
                "            else:\n"
                "                val_images.append(img)\n"
                "                val_targets.append(cls_idx)\n"
                "print({{'dataset_source': dataset_source, 'classes': CUSTOM_CLASSES, 'train_images': len(train_images), 'val_images': len(val_images), 'skipped_members': skipped, 'split_assumption': 'images are independent after exact-duplicate removal'}})\n"
                "\n"
                "ft_output_dir = 'outputs/{stem}_finetuned'\n"
                "import time\n"
                "_t0 = time.perf_counter()\n"
                "fine_tuned_pipe, train_meta = pipe.fit(\n"
                "    train_images=train_images,\n"
                "    train_targets=train_targets,\n"
                "    val_images=val_images,\n"
                "    val_targets=val_targets,\n"
                "    class_names=CUSTOM_CLASSES,\n"
                "    epochs=EPOCHS,\n"
                "    batch_size=BATCH_SIZE,\n"
                "    learning_rate=LEARNING_RATE,\n"
                "    trainable=TRAINABLE,\n"
                "    seed=SEED,\n"
                "    weights_dir=WEIGHTS_DIR,\n"
                "    output_dir=ft_output_dir,\n"
                ")\n"
                "fit_seconds = round(time.perf_counter() - _t0, 1)\n"
                "fine_tuning_meta = train_meta['fine_tuning']\n"
                "import math\n"
                "chance_loss = math.log(len(CUSTOM_CLASSES))\n"
                "final_train_loss = train_meta['history'][-1]['train_loss']\n"
                "print({{\n"
                "    'fine_tuning': 'complete',\n"
                "    'dataset_source': dataset_source,\n"
                "    'classes': CUSTOM_CLASSES,\n"
                "    'train_samples': len(train_images),\n"
                "    'val_samples': len(val_images),\n"
                "    'seconds': fit_seconds,\n"
                "    'trainable_parameters': fine_tuning_meta['trainable_parameters'],\n"
                "    'frozen_parameters': fine_tuning_meta['frozen_parameters'],\n"
                "    'recipe': {{k: fine_tuning_meta[k] for k in ('method', 'optimizer', 'learning_rate', 'epochs', 'steps', 'batch_size', 'seed', 'head_init', 'batchnorm_mode')}},\n"
                "}})\n"
                "for entry in train_meta['history']:\n"
                "    print(entry)\n"
                "print({{'chance_level_loss': round(chance_loss, 4), 'final_train_loss': final_train_loss, 'loss_fell_below_chance': final_train_loss < chance_loss, 'reading': 'a final training loss well below ln(classes) means the head learned the training images; it says nothing yet about held-out images'}})"
            ),
        },
        {
            "md": (
                "<details><summary>Check your reasoning</summary>With the default `TRAINABLE = \"head\"` only the new linear head "
                "changes — 2,562 of 3,775,330 parameters for two classes (the cell prints the exact counts); the backbone built from the "
                "verified snapshot is frozen and stays in eval mode. After duplicate removal the sample has 100 images per class; "
                "20 per class go to validation (`int(100 × 0.2)`), so 160 training and 40 held-out images. Eight epochs over 160 "
                "images at batch size 8 are 160 optimiser steps at learning rate 1e-3. The head starts at zero, so the first "
                "batch's loss is ln(2) ≈ 0.693 and the printed `final_train_loss` should end well below it. Note that `pipe`, the "
                "pretrained 1000-class pipeline, is untouched: `fit` returns a new pipeline and leaves the original model as it was.\n\n"
                "**Expected result (no hosted run of this configuration is recorded yet):** the training loss falls below "
                "chance level within the first epochs. If it does not — or if `TRAINABLE = \"all\"` is used with a small learning "
                "rate and one epoch, which was the previous default of this notebook — the head has not moved from its start and the "
                "held-out accuracy in Section 9 will sit at or below the majority baseline; the review of 2 October 2026 measured "
                "exactly that for the old recipe (7 full-network AdamW steps at 1e-4, batch 4, BatchNorm in train mode: 1 of 6 "
                "held-out images, training loss 2.4–5.0 in every fit, no better than chance over 12 fits).\n\n"
                "**What to notice:** `history` has one entry per epoch; `skipped_members` counts every archive member that "
                "was not used — including the 200 pixel-identical copies — so nothing is dropped silently; `recipe` is what "
                "`model-config.json` records.</details>"
            ),
        },
        {
            "md": (
                "## 9. Fresh-boundary reload and in-notebook evaluation\n\n"
                "To verify artifact integrity across an isolation boundary (simulating a fresh deployment or downstream "
                "container), `MobileNetV4ClassificationPipeline.from_pretrained` loads the newly generated `model.safetensors` "
                "and `model-config.json` directly from `outputs/{stem}_finetuned`. The pipeline re-instantiates the architecture, "
                "restores weights with `strict=True`, and configures the custom class labels. "
                "The cell first checks **reload equivalence**: the reloaded model's scores on every held-out image must match the "
                "in-memory fine-tuned model's to within 1e-5 (a contract check — it stops the notebook if the exported files do not "
                "reproduce the model). The reloaded pipeline is then evaluated across all held-out validation images (`val_images`) "
                "for top-1 accuracy with a 95 % Wilson interval, beside **three references from the same split**: the majority-class "
                "baseline; a **zero-shot reference** — the untouched pretrained 1000-class model, read through the ImageNet-1k classes "
                "that correspond to the dataset classes (`frog` → tree frog, tailed frog, bullfrog; `truck` → the six ImageNet truck classes), "
                "available only when every class has such a mapping; and the fine-tuned model. The **verdict is computed from the "
                "numbers** (above / at / below the majority baseline, and the comparison with the zero-shot reference), never hard-coded. "
                "The first twelve held-out images are listed with true label, predicted label and score, the reloaded model then "
                "classifies one image outside both splits (the Section 4 image) as the new-data inference step, and the "
                "machine-readable evaluation artifacts are written (`outputs/{stem}_validation_predictions.csv`, "
                "`outputs/{stem}_finetuned_evaluation_report.json`). Set `EXTRA_SEEDS` above 0 to repeat the fit with further seeds "
                "and print the spread of held-out accuracy (each repeat costs another fit).\n\n"
                "**Predict before running:** what accuracy does the majority-class baseline get on the default validation split, "
                "how much can one held-out image move the fine-tuned model's accuracy, and which of the three — majority, zero-shot, "
                "fine-tuned — will be highest, given that `frog` and `truck` are already ImageNet classes?"
            ),
            "code": (
                "import csv\n"
                "import math\n\n"
                "EXTRA_SEEDS = 0  # @param {{type:\"integer\"}}\n"
                "RELOAD_TOLERANCE = 1e-5\n"
                "IMAGENET_GROUPS = {{'frog': [30, 31, 32], 'truck': [555, 569, 675, 717, 864, 867]}}  # ImageNet-1k indices that are the dataset classes\n\n\n"
                "def wilson_interval(hits, n, z=1.96):\n"
                "    \"\"\"95 % Wilson score interval for a proportion; (0, 0) when n is 0.\"\"\"\n"
                "    if n == 0:\n"
                "        return (0.0, 0.0)\n"
                "    p = hits / n\n"
                "    denom = 1 + z * z / n\n"
                "    centre = (p + z * z / (2 * n)) / denom\n"
                "    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / denom\n"
                "    return (round(max(0.0, centre - half), 4), round(min(1.0, centre + half), 4))\n\n\n"
                "def compute_verdict(accuracy, majority, zero_shot):\n"
                "    \"\"\"A verdict read from the metrics; the thresholds name the direction, they are not a test.\"\"\"\n"
                "    if accuracy > majority:\n"
                "        verdict = 'above-majority-baseline'\n"
                "    elif accuracy == majority:\n"
                "        verdict = 'at-majority-baseline (no evidence of learning)'\n"
                "    else:\n"
                "        verdict = 'below-majority-baseline (the adapted model is worse than guessing the majority class)'\n"
                "    if zero_shot is None:\n"
                "        return verdict, 'zero-shot reference unavailable: the classes have no ImageNet-1k mapping'\n"
                "    if accuracy > zero_shot:\n"
                "        return verdict, 'fine-tuned model above the zero-shot reference'\n"
                "    if accuracy == zero_shot:\n"
                "        return verdict, 'fine-tuned model equal to the zero-shot reference (adaptation added nothing the pretrained model lacked)'\n"
                "    return verdict, 'fine-tuned model BELOW the zero-shot reference (adaptation lost ground)'\n\n\n"
                "def zero_shot_predict(pretrained_pipe, img, groups, class_names):\n"
                "    \"\"\"Read the pretrained 1000-class scores through the class groups: the group with the highest summed softmax score wins.\"\"\"\n"
                "    scores = {{item['index']: item['score'] for item in pretrained_pipe.predict(img, top_k=NUM_CLASSES)['predictions'][0]['top_k']}}\n"
                "    totals = {{name: sum(scores.get(i, 0.0) for i in groups[name]) for name in class_names}}\n"
                "    return max(totals, key=totals.get), totals\n\n\n"
                "reloaded_pipe = MobileNetV4ClassificationPipeline.from_pretrained(weights_dir=ft_output_dir)\n\n"
                "# Reload equivalence (VER4/VER5): the files on disk must reproduce the in-memory fine-tuned model.\n"
                "max_reload_diff = 0.0\n"
                "for img in val_images:\n"
                "    in_memory = {{t['index']: t['score'] for t in fine_tuned_pipe.predict(img)['predictions'][0]['top_k']}}\n"
                "    from_disk = {{t['index']: t['score'] for t in reloaded_pipe.predict(img)['predictions'][0]['top_k']}}\n"
                "    max_reload_diff = max(max_reload_diff, max(abs(in_memory[i] - from_disk[i]) for i in in_memory))\n"
                "print(f'reload equivalence: max |score difference| over {{len(val_images)}} held-out images = {{max_reload_diff:.2e}} (tolerance {{RELOAD_TOLERANCE:.0e}})')\n"
                "if max_reload_diff > RELOAD_TOLERANCE:\n"
                "    raise RuntimeError(f'the reloaded artifact does not reproduce the fine-tuned model: max |score difference| {{max_reload_diff:.3e}} exceeds {{RELOAD_TOLERANCE:.0e}}')\n\n"
                "# In-notebook evaluation across the held-out validation split\n"
                "val_labels = [CUSTOM_CLASSES[idx] for idx in val_targets]\n"
                "val_predictions = []\n"
                "val_hits = 0\n"
                "per_class_stats = {{cls_name: {{'total': 0, 'correct': 0}} for cls_name in CUSTOM_CLASSES}}\n\n"
                "for img, true_label in zip(val_images, val_labels):\n"
                "    pred_out = reloaded_pipe.predict(img)\n"
                "    pred = pred_out['predictions'][0]\n"
                "    is_correct = (pred['predicted_label'] == true_label)\n"
                "    if is_correct:\n"
                "        val_hits += 1\n"
                "    per_class_stats[true_label]['total'] += 1\n"
                "    if is_correct:\n"
                "        per_class_stats[true_label]['correct'] += 1\n"
                "    val_predictions.append({{\n"
                "        'true_label': true_label,\n"
                "        'predicted_label': pred['predicted_label'],\n"
                "        'predicted_index': pred['predicted_index'],\n"
                "        'confidence': pred['top_k'][0]['score'],\n"
                "        'correct': is_correct,\n"
                "    }})\n\n"
                "val_accuracy = val_hits / max(len(val_labels), 1)\n"
                "majority_class = max(set(val_labels), key=val_labels.count)\n"
                "majority_baseline = val_labels.count(majority_class) / max(len(val_labels), 1)\n"
                "wilson = wilson_interval(val_hits, len(val_labels))\n\n"
                "# Zero-shot reference: the untouched pretrained model on the same held-out split, read through the class groups.\n"
                "zero_shot_accuracy = None\n"
                "zero_shot_note = 'unavailable: not every class maps onto ImageNet-1k classes'\n"
                "if not dataset_fallback_used and all(name in IMAGENET_GROUPS for name in CUSTOM_CLASSES):\n"
                "    zero_hits = sum(zero_shot_predict(pipe, img, IMAGENET_GROUPS, CUSTOM_CLASSES)[0] == true_label for img, true_label in zip(val_images, val_labels))\n"
                "    zero_shot_accuracy = zero_hits / max(len(val_labels), 1)\n"
                "    zero_shot_note = f'pretrained 1000-class model read through ImageNet groups {{ {{k: IMAGENET_GROUPS[k] for k in CUSTOM_CLASSES}} }}; no training'\n"
                "verdict, zero_shot_comparison = compute_verdict(val_accuracy, majority_baseline, zero_shot_accuracy)\n\n"
                "finetuned_eval_report = {{\n"
                "    'task': 'single-label classification fine-tuning evaluation',\n"
                "    'verdict': verdict,\n"
                "    'zero_shot_comparison': zero_shot_comparison,\n"
                "    'validation_samples': len(val_labels),\n"
                "    'classes': CUSTOM_CLASSES,\n"
                "    'metrics': {{\n"
                "        'accuracy': round(val_accuracy, 4),\n"
                "        'accuracy_wilson_95': list(wilson),\n"
                "        'one_image_in_points': round(100.0 / max(len(val_labels), 1), 1),\n"
                "        'majority_baseline_accuracy': round(majority_baseline, 4),\n"
                "        'zero_shot_reference_accuracy': None if zero_shot_accuracy is None else round(zero_shot_accuracy, 4),\n"
                "        'zero_shot_reference': zero_shot_note,\n"
                "        'accuracy_lift_over_baseline': round(val_accuracy - majority_baseline, 4),\n"
                "        'mean_confidence': round(sum(p['confidence'] for p in val_predictions) / max(len(val_predictions), 1), 4),\n"
                "        'reload_max_abs_score_diff': max_reload_diff,\n"
                "    }},\n"
                "    'fine_tuning': fine_tuning_meta,\n"
                "    'dataset_fallback_used': dataset_fallback_used,\n"
                "    'per_class_breakdown': {{\n"
                "        c: {{\n"
                "            'total': s['total'],\n"
                "            'correct': s['correct'],\n"
                "            'accuracy': round(s['correct'] / s['total'], 4) if s['total'] > 0 else 0.0,\n"
                "        }} for c, s in per_class_stats.items()\n"
                "    }},\n"
                "    'fresh_boundary_source': reloaded_pipe.source,\n"
                "}}\n\n"
                "eval_report_path = f'outputs/{stem}_finetuned_evaluation_report.json'\n"
                "with open(eval_report_path, 'w', encoding='utf-8') as handle:\n"
                "    json.dump(finetuned_eval_report, handle, indent=2, ensure_ascii=False)\n\n"
                "val_preds_csv_path = f'outputs/{stem}_validation_predictions.csv'\n"
                "with open(val_preds_csv_path, 'w', encoding='utf-8', newline='') as handle:\n"
                "    writer = csv.DictWriter(handle, fieldnames=['sample_index', 'true_label', 'predicted_label', 'correct', 'confidence'])\n"
                "    writer.writeheader()\n"
                "    for idx, p in enumerate(val_predictions):\n"
                "        writer.writerow({{'sample_index': idx, 'true_label': p['true_label'], 'predicted_label': p['predicted_label'], 'correct': p['correct'], 'confidence': f\"{{p['confidence']:.6f}}\"}})\n\n"
                "print('=== Fine-Tuned Model In-Notebook Evaluation (same held-out split for every row) ===')\n"
                "print(f\"Validation Samples: {{len(val_labels)}} | Classes: {{CUSTOM_CLASSES}} | one image = {{100.0 / max(len(val_labels), 1):.1f}} points\")\n"
                "print(f\"Majority Baseline:  {{majority_baseline:.2%}} (predicting '{{majority_class}}')\")\n"
                "print('Zero-shot reference:' + (f' {{zero_shot_accuracy:.2%}} ({{zero_shot_note}})' if zero_shot_accuracy is not None else f' {{zero_shot_note}}'))\n"
                "print(f\"Fine-tuned (reloaded): {{val_accuracy:.2%}} ({{val_hits}}/{{len(val_labels)}} correct; 95 % Wilson interval {{wilson[0]:.2%}}-{{wilson[1]:.2%}})\")\n"
                "print(f\"Lift Over Baseline: {{val_accuracy - majority_baseline:+.2%}}\")\n"
                "print('VERDICT:', verdict, '|', zero_shot_comparison)\n"
                "print('held-out images (first 12): true -> predicted (score)')\n"
                "for p in val_predictions[:12]:\n"
                "    print(f\"  {{p['true_label']:>8}} -> {{p['predicted_label']:<8}} ({{p['confidence']:.3f}}) {{'ok' if p['correct'] else 'WRONG'}}\")\n"
                "print(json.dumps(finetuned_eval_report['metrics'], indent=2))\n\n"
                "# New-data inference: the reloaded model on an image outside both splits (the Section 4 image).\n"
                "new_data = reloaded_pipe.predict(image)['predictions'][0]\n"
                "print({{'new_data_inference': {{'image': image_name, 'predicted_label': new_data['predicted_label'], 'score': round(new_data['top_k'][0]['score'], 4), 'note': 'the gradient (or your BYOD image) belongs to neither class; the head answers anyway, which is why a softmax score is not a probability of being right'}}}})\n\n"
                "seed_spread = None\n"
                "if EXTRA_SEEDS > 0:\n"
                "    accuracies = [round(val_accuracy, 4)]\n"
                "    for extra in range(1, EXTRA_SEEDS + 1):\n"
                "        repeat_pipe, repeat_meta = pipe.fit(train_images=train_images, train_targets=train_targets, val_images=val_images, val_targets=val_targets, class_names=CUSTOM_CLASSES, epochs=EPOCHS, batch_size=BATCH_SIZE, learning_rate=LEARNING_RATE, trainable=TRAINABLE, seed=SEED + extra, weights_dir=WEIGHTS_DIR)\n"
                "        accuracies.append(repeat_meta['history'][-1].get('val_accuracy'))\n"
                "    seed_spread = {{'seeds': [SEED + i for i in range(EXTRA_SEEDS + 1)], 'held_out_accuracy': accuracies, 'min': min(accuracies), 'max': max(accuracies)}}\n"
                "    finetuned_eval_report['seed_spread'] = seed_spread\n"
                "    with open(eval_report_path, 'w', encoding='utf-8') as handle:\n"
                "        json.dump(finetuned_eval_report, handle, indent=2, ensure_ascii=False)\n"
                "    print({{'seed_spread': seed_spread}})\n"
            ),
        },
        {
            "md": (
                "<details><summary>Check your reasoning</summary>The default validation split holds 20 `frog` and 20 `truck` "
                "images, so the majority-class baseline is exactly 50 % (the two classes tie). Forty images make every accuracy a "
                "multiple of 2.5 points, and the Wilson interval printed beside it is wide (about ±15 points at 50 %, narrower near "
                "the ends), so read small differences between rows as noise. **Expected ordering (no hosted run of this configuration "
                "is recorded yet; record yours in the Conclusion):** the zero-shot reference should be highest or tied — `frog` and "
                "`truck` are ImageNet-1k classes, so the untouched pretrained model already solves this task (the review of 2 October "
                "2026 measured 6 of 6 held-out and 26 of 26 training images on the previous split); the fine-tuned head, trained on "
                "features that already separate the classes, should land well above the majority baseline and near the zero-shot "
                "reference. **How to read a lift at or below zero:** it means the head did not learn — check that `final_train_loss` "
                "in Section 8 fell below ln(2); if it did not, the recipe (learning rate, epochs, `TRAINABLE`) is the problem, not the "
                "data — and the verdict line says so instead of calling the run a success. If the download fell back to synthetic "
                "stripes, the baseline is again 50 % (2 + 2 images), there is no zero-shot reference, and the result is about stripes.\n\n"
                "**What to notice:** `reload equivalence` is a contract check on the exported files; `fresh_boundary_source` shows "
                "the reloaded model came from `outputs/{stem}_finetuned/` on disk, not from the object in memory; "
                "`new_data_inference` shows the adapted head answering for an image that belongs to neither class.\n\n"
                "**Change one thing (optional):** in Section 8 set `TRAINABLE = \"all\"`, `EPOCHS = 1`, `LEARNING_RATE = 1e-4`, "
                "`BATCH_SIZE = 4` — the recipe this notebook shipped before — and re-run Sections 8–9. Predict first: will the "
                "training loss fall below ln(2), and where will the verdict land? Then explain the difference from the `recipe` "
                "line (BatchNorm mode, trainable count, steps).</details>"
            ),
        },
        {
            "md": (
                "## 10. Export outputs and provenance\n\n"
                "Machine-readable JSON preserves the full prediction (argmax decision and the rank-ordered top-k scores), "
                "the evaluation report, the fine-tuning training history and in-notebook evaluation metrics, the sample identity and digest, "
                "the notebook's source (repository, revision, embedded module digest, generator), the model identifier, the immutable model "
                "revision, and the runtime identity (Python, `torch`, `timm`, device). The rank-ordered top-k table and fine-tuned validation "
                "predictions are written as CSV files so class ordering survives downstream use. Deployable fine-tuned model artifacts and evaluation "
                "reports are published in `outputs/{stem}_finetuned/` and `outputs/`. No credentials are recorded."
            ),
            "code": (
                "import csv\n\n"
                "payload = {{\n"
                "    'prediction': result,\n"
                "    'evaluation_report': report,\n"
                "    'input_manifest': input_manifest,\n"
                "    'fine_tuning': {{\n"
                "        'history': train_meta['history'],\n"
                "        'classes': CUSTOM_CLASSES,\n"
                "        'recipe': fine_tuning_meta,\n"
                "        'dataset_source': dataset_source,\n"
                "        'dataset_fallback_used': dataset_fallback_used,\n"
                "        'skipped_members': skipped,\n"
                "        'seconds': fit_seconds,\n"
                "        'evaluation': finetuned_eval_report,\n"
                "    }},\n"
                "    'sample': {{'kind': sample_kind, 'name': image_name, 'size': list(image.size), 'rgb_sha256': sample_sha256, 'ground_truth_index': ground_truth}},\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'model_id': MODEL_ID,\n"
                "    'model_revision': MODEL_REVISION,\n"
                "    'model_license': MODEL_LICENSE,\n"
                "    'runtime': {{\n"
                "        'python': platform.python_version(),\n"
                "        'torch': torch.__version__,\n"
                "        'timm': timm.__version__,\n"
                "        'device': pipe.device,\n"
                "    }},\n"
                "}}\n"
                "with open('outputs/{stem}_result.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(payload, handle, indent=2, ensure_ascii=False)\n"
                "with open('outputs/{stem}_top_k.csv', 'w', encoding='utf-8', newline='') as handle:\n"
                "    writer = csv.writer(handle)\n"
                "    writer.writerow(['image', 'rank', 'index', 'label', 'score'])\n"
                "    for rank, item in enumerate(prediction['top_k'], start=1):\n"
                "        writer.writerow([image_name, rank, item['index'], item['label'], f\"{{item['score']:.6f}}\"])\n"
                "print({{'outputs': sorted(os.listdir('outputs')), 'finetuned': sorted(os.listdir(ft_output_dir))}})\n"
                "print(['outputs/{stem}_finetuned/model.safetensors', 'outputs/{stem}_finetuned/model-config.json'])"
            ),
        },
    ],
    "closing": (
        "## Interpretation and limits\n\n"
        "The predicted label is the argmax of a softmax over the fixed 1000-class ImageNet-1k label space (or custom "
        "class names when fine-tuned); the `score` values are uncalibrated softmax outputs, not probabilities of "
        "correctness, and the pipeline ships no threshold. On the synthetic gradient the label is meaningless by "
        "construction and the evaluation report says `not-measurable`; a `top_k_accuracy` value shown for a single "
        "BYOD image is tutorial evidence for that one image and must not be generalized to a domain, camera, or class "
        "distribution. Images whose subject is outside ImageNet-1k, line drawings, medical or satellite imagery, and "
        "subjects near the image border (removed by the center crop) all degrade results in ways the pipeline does not "
        "detect. The pipeline provides no detection, segmentation, multi-label, OCR, or open-vocabulary capability.\n\n"
        "**Reading the adaptation result.** Three numbers from the same 40 held-out images sit side by side in Section 9. "
        "The zero-shot reference is expected to be the highest or tied: `frog` and `truck` are ImageNet-1k classes, so the "
        "pretrained model already solves the default task without any training, and the fine-tune cannot be expected to add "
        "accuracy on it — what it demonstrates is the adaptation *contract* (a new head trained on frozen features, exported, "
        "reloaded with verified equivalence and scored against baselines), on a task whose ceiling is visible. The fine-tuned "
        "head should land well above the majority baseline; if your run's verdict is `at` or `below` the majority baseline, "
        "the head did not learn (check `final_train_loss` against ln(2) in Section 8) and the result is a failed adaptation, "
        "not a success, whatever the mean confidence says. On your own classes — which are not ImageNet classes — the "
        "zero-shot reference is unavailable and the majority baseline is the floor to beat; the previous recipe of this "
        "notebook (full-network training for seven steps) sat at or below that floor in every recorded run, which is why the "
        "default is now a head-only probe with a zero-initialised head and 160 seeded, shuffled steps.\n\n"
        "Successful execution proves that the recorded repository revision's pipeline module, carried in this notebook, "
        "can acquire and digest-verify the pinned model, validate the demonstrated input, execute the public pipeline "
        "path, perform in-kernel adaptation and show its result against a majority baseline and a zero-shot reference, reload the "
        "verified artifact bundle with equivalence checked, and emit the shown machine-readable "
        "outputs in the tested runtime — without the repository being reachable. It does **not** establish benchmark "
        "superiority, deployment calibration, safety for high-consequence decisions, or production fitness on an unseen domain.\n\n"
        "**Next experiments:** enable `USE_BYOD` with a photograph of a known ImageNet class and its index to see the "
        "report switch to `sample-sanity` with `top_k_accuracy` at k=1 and k=5; supply your own multi-class dataset folder "
        "to `pipe.fit` to adapt to your domain; classify a batch (up to `MAX_BATCH`) of labelled images from your own "
        "domain and compare top-1 against the majority-class baseline of that set; inspect how the top-1 score moves when "
        "the subject is moved toward the border of the frame.\n\n"
        "## Troubleshooting\n\n"
        "- **Section 1 stops with \"This notebook needs a Linux x86_64 runtime\"** — you are on Windows, macOS or an ARM machine. Use Google Colab, Kaggle or a Linux x86_64 Jupyter server.\n"
        "- **The uv wheel fails its size/SHA-256 check, or a download in Section 1 times out** — run Section 1 again; a complete environment is reused and an incomplete one is finished. If it repeats, the network is blocking or altering `files.pythonhosted.org` or `pypi.org`.\n"
        "- **You re-ran Section 1 on its own** — nothing is lost: it keeps the running worker and every variable, so the cells after it keep working. After a session restart, run from the top.\n"
        "- **\"The isolated environment's Python process exited\"** — usually out of memory. Restart the session and choose **Run all**.\n"
        "- **Section 3 reports a size or SHA-256 mismatch, or cannot reach the Hub** — `verify_snapshot` names the file. Delete the folder Section 3 prints as `weights_dir` and run Section 3 again.\n"
        "- **Section 8 prints \"public sample dataset download failed\"** — the run continues on synthetic stripes and says so in `dataset_source` and `result.json` (`dataset_fallback_used`); the accuracy is then about stripes, not photographs, and there is no zero-shot reference. Re-run Section 8 when the network is back.\n"
        "- **Section 8 stops with \"Sample dataset SHA-256 mismatch\"** — the downloaded archive is not the pinned one (a proxy or a changed file); nothing was trained. Check the network path and run Section 8 again.\n"
        "- **Section 9 stops with \"the reloaded artifact does not reproduce the fine-tuned model\"** — the exported files in `outputs/` are stale or damaged; delete the `_finetuned` folder and re-run Sections 8–9.\n"
        "- **The verdict is at or below the majority baseline** — the head did not learn: confirm `final_train_loss` < ln(classes) in Section 8; if not, raise `EPOCHS` or `LEARNING_RATE`, or keep `TRAINABLE = \"head\"`.\n"
        "- **BYOD: \"BYOD path … does not exist\"** — the path is relative to the working directory printed in the message; give the full path of the image or `.zip`.\n"
        "- **BYOD: \"the upload dialog exists only in Google Colab\"** — on Kaggle or Jupyter, copy the file into the runtime (or attach it as a dataset) and set `BYOD_PATH` / `BYOD_DATASET_PATH`.\n"
        "- **BYOD: \"Upload exactly one …\"** — the dialog was cancelled or several files were chosen; run the cell again.\n"
        "- **BYOD: \"Class 'x' has fewer than 2 images\" or \"at least 2 distinct classes\"** — the archive is below the effective minimum (2 classes, 2 images per class when un-split); add images.\n"
        "- **BYOD: \"<member>: Pillow cannot decode this archive member\"** — that file inside the zip is corrupt or not an image; remove it.\n\n"
        "## Glossary\n\n"
        "- **ImageNet-1k** — the 1000-class label space the pretrained head predicts; every image gets one of these labels unless you fine-tune a new head.\n"
        "- **Logit / softmax score** — the network's raw output per class, and the same values squashed to sum to 1 over all classes. A softmax score is uncalibrated: it is not the probability that the label is right.\n"
        "- **Argmax / top-k** — the single highest-scoring class, and the k highest-scoring classes in descending order.\n"
        "- **Centre crop (`crop_pct = 0.875`)** — resize to 256 px, then keep the central 224×224, so content near the border is discarded before the model sees it.\n"
        "- **Backbone / classification head** — the convolutional feature extractor, and the final linear layer that maps features to class scores; the default adaptation freezes the backbone and trains only the new head (a linear probe).\n"
        "- **Trainable / frozen parameters** — the weights the optimiser may change versus those kept as loaded; printed by Section 8 and recorded in `model-config.json`.\n"
        "- **BatchNorm (eval vs train mode)** — layers that normalise activations with running statistics; in train mode small batches overwrite those statistics, so head-only adaptation keeps the network in eval mode.\n"
        "- **Zero-shot reference** — the untouched pretrained model scored on the same held-out split through the ImageNet classes that correspond to the dataset classes; the ceiling the fine-tune is compared with.\n"
        "- **Wilson interval** — a 95 % interval for an accuracy measured on n images; on 40 images it is roughly ±15 points at 50 %.\n"
        "- **Epoch / batch size / learning rate** — one pass over the training images; images per update step; the size of each AdamW step.\n"
        "- **Cross-entropy** — the training loss: low when the true class gets a high softmax score.\n"
        "- **Validation split** — images held out of training and scored only after it; here 20 % per class with a fixed seed.\n"
        "- **Majority-class baseline** — the accuracy of always answering the most common validation class; a model that cannot beat it has learned nothing usable.\n"
        "- **Fresh-boundary reload** — loading the exported `model.safetensors` and `model-config.json` from disk into a new pipeline, so the evaluation tests the files you would ship.\n"
        "- **`sample-sanity` / `not-measurable`** — the evaluation verdicts: a one-image check against a known label, and no ground truth at all.\n"
        "- **Isolated environment** — the separate Python 3.12.12 environment Section 1 builds from the hash lock; every later cell runs there.\n"
        "- **BYOD** — bring your own data: your image or labelled dataset through the same cells.\n\n"
        "## Conclusion (your notes)\n\n"
        "Optional — fill in from **your** run:\n\n"
        "- On the gradient the top-1 class was ___ with score ___; I read it as ___ because the sample has no ground truth.\n"
        "- Fine-tuning used ___ training and ___ validation images from ___ (`dataset_source`).\n"
        "- The training loss went from ___ (ln 2 = 0.693) to ___ over ___ steps with ___ trainable parameters.\n"
        "- On the same 40 held-out images: majority ___, zero-shot ___, fine-tuned ___ (Wilson ___–___); the verdict was ___.\n"
        "- One reason not to trust this number for my own images yet: ___ (for example forty validation images, classes the pretrained model already knows, or a different domain).\n\n"
        "## References\n\n"
        "- Repository README: https://github.com/kurtvalcorza/mobilenetv4-classification-pipeline/blob/main/README.md\n"
        "- Repository model card: https://github.com/kurtvalcorza/mobilenetv4-classification-pipeline/blob/main/MODEL_CARD.md\n"
        "- Weight provenance: https://github.com/kurtvalcorza/mobilenetv4-classification-pipeline/blob/main/docs/WEIGHTS.md\n"
        "- Upstream model: https://huggingface.co/{MODEL_ID}\n"
        "- Upstream library: https://github.com/huggingface/pytorch-image-models\n"
        "- MobileNetV4 — Universal Models for the Mobile Ecosystem: https://arxiv.org/abs/2404.10518"
    ),
}
